//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChoixReponse
    {
        public int id { get; set; }
        public Nullable<int> idSondage { get; set; }
        public Nullable<int> idReponse { get; set; }
    
        public virtual Sondage Sondage { get; set; }
        public virtual Reponse Reponse { get; set; }
    }
}
