//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commentaires
    {
        public int Id { get; set; }
        public string Auteur { get; set; }
        public string Contenu { get; set; }
        public System.DateTime Date_du_commentaire { get; set; }
        public int Id_Article { get; set; }
    
        public virtual Articles Articles { get; set; }
    }
}
