//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models.Bdd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composant
    {
        public int idFormulaire { get; set; }
        public int idQuestion { get; set; }
        public int idTypeReponse { get; set; }
        public int id { get; set; }
    
        public virtual Formulaire Formulaire { get; set; }
        public virtual Question Question { get; set; }
        public virtual TypeReponse TypeReponse { get; set; }
    }
}
